{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/dd/Actions/purl/Service/UploadOffline.action",
    "OnFailure": "/dd/Actions/purl/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}